apiVersion: v1
kind: ResourceQuota
metadata:
  name: wer-quota
  namespace: wer
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
    persistentvolumeclaims: "5"