apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ccc-role
  namespace: ccc
rules:
- apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
  resources: ["pods", "services", "deployments", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ccc-role-binding
  namespace: ccc
subjects:
- kind: User
  name: 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ccc-role
  apiGroup: rbac.authorization.k8s.io